// Generated by CoffeeScript 1.4.0
var ConfigError,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

module.exports = ConfigError = (function(_super) {

  __extends(ConfigError, _super);

  function ConfigError(message) {
    ConfigError.__super__.constructor.call(this, message);
  }

  return ConfigError;

})(Error);
